sudo: required
language: generic
services: docker
tex-config:
- tex-scheme=medium
- push-type=branch
- build-pattern=AlvaroZornoza_CV.tex
- packages=lipsum, blindtext, inputenc, babel, sectsty, microtype, amsmath, amsfonts,
  amsthm, graphicx, xcolor, geometry, attachfile, fontawesome, wrapfig, hyperref,
  xcolor
env:
  global:
  - IS_TRAVIS=true
  matrix:
  - secure: aimSca+FpF+fO8mHzCUyg8oAY9bSry8bWcgy3DwQ9W1Kn+Tu6fJ80WvllN8stFf7uJSLv5Xfro1ec9NuudgjzTYOrhhflG9CV6BuxNF6XTaD/IJb+5Edf/SWt4bK5q2lLyI173ncGODpCHT/fglksyrXbbCOvkxq11yVXscFIMtFL7yHf7KrRqVINhRGnASYpcw4R+K3n6EDOZUf9yDghsfG5geN9LGMVLA0GngJaUvmNkQJCwClwUIJbQzYsdk2OAtOyPT4UjcE5hUNc1h4lanXguvplVYneBPqWwAToxGj3onB6xYb+klx5giM1rLv2dPftgJSNBjxFwqwA/SF+JSYAVmM0BDaLTn8JYXnaFwXRYmHaVl6dZUYu4CZJREYgj0LuORBOebHduG7DQS4avoKY/fib1rNDaay5AoLvMJZGv0XA7EVhq7yxO8U+w/x/8c1g9INjmdoSXVP2tOS7Nt3Lf6HxUq+VDvFiMMgFXxMRcdV9hzHnbIMo4UAXJ+pQ8Hg0RHt1F6w+LP1CB2WWWBjJuIMmLL1R+WDdf2fU13xxSZHWQJgYJ8gKcDAOcUXvayyxGEj/vcLlphQYnXrIrsZCI/C/Km0p46Prup8ZQDnM3pkpbB5DrHWj7/s8BGSwGyrn3cSZnIOjn6h6TAZ+5zLBTIbz9oFfxkHkKavozg=
script:
- chmod +x .travis/travis-texbuild.sh
- ".travis/travis-texbuild.sh"
if: commit_message =~ /^((?!Travis).)*$/
